/**
 * roster/library.ts — the fs + parse glue between the campaign and the vendored
 * card builder. Resolves a model name against the bundled MegaMek library, reads
 * the .mtf/.blk, and parses it with the card core (which runs unchanged in Node).
 * Impure by design; the pure derivation lives in roster/derive.ts.
 *
 * The library is the same data the battle tracker serves — generated by
 * extract-units into cards/dist-web (or cards/public before a web build). If it
 * hasn't been generated yet, every call returns null and callers fall back to
 * whatever the campaign already had.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { convertAny } from '../../cards/src/core/index.js';
import { buildNameIndex, normalizeName, resolveModel } from '../../cards/src/web/handoff-import.js';
import type { UnitIndexEntry } from '../../cards/src/web/handoff-import.js';
import { deriveUnitFields } from './derive.js';
import type { DerivedUnitFields, ParsedCardLike } from './derive.js';

const here = dirname(fileURLToPath(import.meta.url));
// Roots that may hold units-index.json + units/ + bv-index.json, best first.
const ROOTS = ['../../cards/dist-web', '../../cards/public'].map(r => join(here, r));

interface Lib {
  root: string;
  index: Map<string, UnitIndexEntry>;
  bv: Record<string, number>;
  role: Record<string, string>;
}
let cache: Lib | null = null;
let loaded = false;

function lib(): Lib | null {
  if (loaded) return cache;
  loaded = true;
  for (const root of ROOTS) {
    const idxPath = join(root, 'units-index.json');
    if (!existsSync(idxPath)) continue;
    try {
      const entries = JSON.parse(readFileSync(idxPath, 'utf8')) as UnitIndexEntry[];
      const readJson = <T>(name: string, fallback: T): T => {
        const p = join(root, name);
        return existsSync(p) ? (JSON.parse(readFileSync(p, 'utf8')) as T) : fallback;
      };
      const bv = readJson<Record<string, number>>('bv-index.json', {});
      const role = readJson<Record<string, string>>('role-index.json', {});
      cache = { root, index: buildNameIndex(entries), bv, role };
      return cache;
    } catch {
      /* try the next root */
    }
  }
  return null;
}

/** Is the bundled unit library present (has it been extracted/built)? */
export function isLibraryAvailable(): boolean {
  return lib() !== null;
}

/** The unit index entries (name/path/category/era), or null with no library. */
export function libraryIndex(): UnitIndexEntry[] | null {
  const L = lib();
  return L ? [...L.index.values()] : null;
}

const bvKey = (s: string): string => s.toLowerCase().replace(/\s+/g, ' ').trim();
const fileStem = (p: string): string =>
  (p.replace(/\\/g, '/').split('/').pop() ?? '').replace(/\.(mtf|blk)$/i, '');

export interface LoadedCard {
  model: string;
  path: string;
  text: string;
  parsed: ParsedCardLike;
  bv?: number;
  role?: string;
}

/** Resolve a model name to a parsed card + its raw text + BV, or null. */
export function loadCardByModel(model: string): LoadedCard | null {
  const L = lib();
  if (!L) return null;
  const hit = resolveModel(model, L.index);
  if (!hit) return null;
  const file = join(L.root, 'units', hit.path);
  if (!existsSync(file)) return null;
  try {
    const text = readFileSync(file, 'utf8');
    const parsed = convertAny(text, hit.path) as unknown as ParsedCardLike;
    const bv = L.bv[bvKey(fileStem(hit.path))] ?? L.bv[bvKey(hit.name)];
    const role = L.role[bvKey(fileStem(hit.path))] ?? L.role[bvKey(hit.name)];
    return { model, path: hit.path, text, parsed, ...(bv != null ? { bv } : {}), ...(role ? { role } : {}) };
  } catch {
    return null; // unparseable / unsupported unit type — caller keeps its own data
  }
}

/** Derive campaign Unit fields for a model name straight from the library. */
export function deriveFieldsForModel(model: string): DerivedUnitFields | null {
  const c = loadCardByModel(model);
  return c ? deriveUnitFields(c.parsed, c.text, c.bv, c.role) : null;
}

/**
 * Search the bundled library by name substring (for the campaign editor's unit
 * picker). Returns up to `limit` matches with the derived class + BV so the editor
 * can author a correct unit; the rest fills in via enrichment on load.
 */
export function searchLibrary(
  query: string, limit = 20,
): Array<{ name: string; class: string; bv?: number }> {
  const L = lib();
  const q = normalizeName(query);
  if (!L || q.length < 2) return [];
  const out: Array<{ name: string; class: string; bv?: number }> = [];
  for (const entry of L.index.values()) {
    if (!normalizeName(entry.name).includes(q)) continue;
    const d = deriveFieldsForModel(entry.name);
    if (d) out.push({ name: entry.name, class: d.class, ...(d.bv != null ? { bv: d.bv } : {}) });
    if (out.length >= limit) break;
  }
  return out;
}
